# Generated by Django 4.2.1 on 2023-07-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='id',
            new_name='branch_id',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='id',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='id',
            new_name='state_id',
        ),
    ]
